apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-demo-helm-dev
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/vishnumohandas1994/argocd-gitops-practice.git
    targetRevision: main
    path: gitops-demo-chart

    helm:
      valueFiles:
        - values-dev.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: helm-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
