apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-demo
  namespace: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gitops-demo
  template:
    metadata:
      labels:
        app: gitops-demo
    spec:
      containers:
        - name: gitops-demo
          image: nginx:does-not-exist
          ports:
            - containerPort: 80
